version: '3.9'

services:
  redis:
    image: redis:7
    container_name: redis
    ports:
      - '6379:6379'

  postgres:
    container_name: postgres
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - '5433:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - pinotheca

volumes:
  postgres_data:

networks:
  pinotheca:
